{
    'name': 'Rahil Manufacture',
    'version': '1.0',
    'sequence': '20',
    'description': "Manufacture in Details",
    'installable': True,
    'license': 'LGPL-3',
    'application': True,
    'category': 'Sales',
    'depends': ['base', 'sale', 'rahil_sales', 'mrp', 'l10n_in_sale', 'hr', 'stock'],
    'data': [
        'data/sequence.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'wizard/select_order_line_view.xml',
        'wizard/backorder_confirmation.xml',
        'views/sale_order.xml',
        'views/mrp_production.xml',
        'views/sale_order_line.xml',
        'views/product.xml',
        'views/breakdown_analysis.xml',
        'views/work_entry.xml',
        'views/quality_control.xml',
        'views/slitting_metalised_view.xml',
        'views/mrp_rewinding_view.xml',
        'views/stock_production_lot.xml',
        'reports/report_qc_slitting.xml',
        'reports/slitting_roll_qc_template.xml',
        'reports/final_roll_sticker_report.xml',
        'reports/final_roll_sticker_template.xml',
        'reports/jumbo_roll_sticker_report.xml',
        'reports/jumbo_roll_sticker_template.xml',
        'reports/final_roll_export_sticker_template.xml',
    ],
}